# ABOUTME: Student-facing Pydantic models for the moulinette evaluation contract.
# ABOUTME: Students copy this file into their project — it defines the JSON schema the moulinette expects.
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class StepMetrics(BaseModel):
    """Metrics for a single agent step.

    Each step corresponds to one LLM generate → sandbox execute cycle.
    All fields are required for evaluation — empty strings are acceptable
    for steps where a field doesn't apply (e.g., no sandbox execution).
    """
    step: int = Field(..., description="1-indexed iteration number")
    input_tokens: int = Field(..., description="Tokens sent to the LLM for this step")
    output_tokens: int = Field(..., description="Tokens generated by the LLM for this step")
    request_time_ms: float = Field(..., description="Wall-clock time for the LLM API call in milliseconds")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO 8601 timestamp of when this step was recorded")
    api_url: str = Field(default="", description="Base URL of the LLM API endpoint (e.g., 'https://openrouter.ai/api/v1')")
    model_name: str = Field(default="", description="Model identifier used for this step (e.g., 'qwen/qwen3-235b-a22b-2507')")
    llm_output: str = Field(default="", description="Raw text generated by the LLM before code extraction")
    sandbox_input: str = Field(default="", description="Python code sent to the sandbox for execution")
    sandbox_output: str = Field(default="", description="Sandbox execution result (stdout/stderr/error message)")
    retries: int = Field(default=0, description="Number of LLM API retries before getting a successful response (0 = first attempt succeeded)")


class SolutionOutput(BaseModel):
    """Output from student solution — required format for evaluation.

    This is the JSON structure your agent must produce and write to solution.json.
    The moulinette validates this against task correctness and metrics limits.
    """
    task_id: str = Field(..., description="Task identifier (MBPP task_id as string, or SWE-bench instance_id)")
    benchmark: str = Field(..., description="Benchmark type: 'mbpp' or 'swebench'")
    success: bool = Field(..., description="Whether the agent believes it solved the task")
    solution: str = Field(..., description="For MBPP: the Python function code. For SWE-bench: the git patch (diff)")
    iterations: int = Field(..., description="Number of agent loop iterations used")
    total_requests: int = Field(..., description="Total number of LLM API requests made (including retries)")
    total_input_tokens: int = Field(..., description="Sum of input_tokens across all steps")
    total_output_tokens: int = Field(..., description="Sum of output_tokens across all steps")
    total_time_seconds: float = Field(..., description="Wall-clock time from agent start to finish")
    steps: List[StepMetrics] = Field(default_factory=list, description="Per-step metrics — one entry per agent iteration")
    system_prompt: str = Field(default="", description="Full system prompt sent to the LLM (for provenance checking)")
    error: Optional[str] = Field(default=None, description="Error message if the agent failed (None if successful)")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO 8601 timestamp of when the solution was produced")


class SandboxConfig(BaseModel):
    """Configuration for the secure code execution sandbox.

    Uses an allowlist approach: only imports in authorized_imports are permitted.
    Everything else is blocked by default.
    """
    authorized_imports: List[str] = Field(default_factory=list, description="List of allowed import names (e.g., ['math', 'json', 're']). Glob patterns like 'math.*' are supported.")
    allowed_directories: List[str] = Field(default_factory=list, description="List of filesystem paths the sandbox can access (e.g., ['/testbed', '/tmp/agent'])")
    max_execution_time_seconds: int = Field(default=30, description="Maximum wall-clock time for a single sandbox execution before timeout")
    max_memory_mb: int = Field(default=512, description="Maximum memory in megabytes for sandbox execution")


class MBPPTaskInput(BaseModel):
    """Input for an MBPP task — provided by the moulinette.

    Your agent receives this as the task definition to solve.
    """
    task_id: int = Field(..., description="MBPP task identifier (integer)")
    task_definition: str = Field(..., description="Natural language description of the function to implement")
    function_definition: str = Field(..., description="Function signature (e.g., 'def solve(nums):')")
    test_imports: List[str] = Field(default_factory=list, description="Import statements needed to run the public tests")
    test_list: List[str] = Field(default_factory=list, description="Public test assertions the solution must pass")


class SWEBenchTaskInput(BaseModel):
    """Input for a SWE-bench task — provided by the moulinette.

    Your agent receives this and must produce a git patch that fixes the issue.
    """
    instance_id: str = Field(..., description="SWE-bench instance identifier (e.g., 'sympy__sympy-23534')")
    problem_statement: str = Field(..., description="The GitHub issue description — what needs to be fixed")
    docker_image: str = Field(..., description="Full Docker image name to pull (e.g., 'swebench/sweb.eval.x86_64.sympy_1776_sympy-23534:latest')")
    eval_script: str = Field(..., description="Bash script to run inside the container to evaluate the patch")
    hints_text: str = Field(default="", description="Optional hints about the issue (may be empty)")
    repo: str = Field(default="", description="Repository name (e.g., 'sympy/sympy')")
